version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable

    steps:
      - checkout

      # Install Docker client inside the CircleCI Docker executor
      - setup_remote_docker
      
      # Build the Docker image using Dockerfile
      - run:
          name: Build Docker Image
          command: |
            docker build -t automationimage .

      # Optionally, you can run tests or other commands inside the Docker container
      - run:
          name: Run Tests inside Docker Container
          command: |
            docker run -v /root/project/reports:/home/seluser/stockwellautomation/qa-stockwell/test-output automationimage  # Example command to run tests

      # Store test report files as artifacts
      - store_artifacts:
          path: /root/project/reports
          destination: test-reports


workflows:
  version: 2
  build:
    jobs:
      - build
      
