version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable

    steps:
      - run:
          name: Flush Reports from Artifacts
          command: |
            rm -rf /root/project/

      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Build Docker Image
          command: |
            docker build -t automationimage .

      - run:
          name: Run Tests inside Docker Container
          command: |
            pwd
        
            # Run tests inside the Docker container
            docker run -v /root/project/qa-stockwell/TestReports:/home/seluser/stockwellautomation/qa-stockwell/TestReports automationimage bash -c '
              pwd
              ls -al /root/project/qa-stockwell/TestReports
              ls -al /home/seluser/stockwellautomation/qa-stockwell/TestReports
            '

      - store_artifacts:
          path: /root/project/qa-stockwell/TestReports
          destination: test-reports

      - run:
          name: List Files in the Folder
          command: |
            pwd
            ls -al 
            ls -al /root/project/qa-stockwell/TestReports

workflows:
  version: 2
  build:
    jobs:
      - build
