version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:latest
    
    steps:
      - checkout
          

      # Install wget and unzip (if not already installed in base image)
      - run:
          name: Install wget and unzip
          command: |
            apt-get update && apt-get install -y wget unzip

      # Install Java using apt-get non-interactively
      - run:
          name: Install Java
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get install -y openjdk-17-jdk
            java -version  # Verify Java installation

      # Install Gradle using wget
      - run:
          name: Install Gradle
          command: |
            wget -q --show-progress --progress=bar:force:noscroll -O /tmp/gradle-7.5.1-bin.zip https://services.gradle.org/distributions/gradle-7.5.1-bin.zip
            unzip -d /opt/gradle /tmp/gradle-7.5.1-bin.zip
            export PATH=$PATH:/opt/gradle/gradle-7.5.1/bin

     
     # Ensure Gradle Wrapper is present and executable
      - run:
          name: Initialize Gradle Wrapper
          command: |
            pwd
            ls -l
            cd /root/project/qa-stockwell
            chmod +x gradlew
            ./gradlew wrapper --gradle-version 7.5.1
            
            
      # Run Gradle tasks for project build and test
      - run:
           name: Run Gradle Tasks
           command: |
            pwd
            ls -l
            cd /root/project/qa-stockwell
            chmod +x gradlew
            ./gradlew --refresh-dependencies clean build --info
            ./gradlew build --warning-mode all
            ./gradlew test -Dtestng.outputDir=/test-output -Dtestng.xmlpath=testng.xml

workflows:
  version: 2
  build:
    jobs:
      - build
