version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable

    steps:
      - checkout

      # Install Docker client inside the CircleCI Docker executor
      - setup_remote_docker:
          docker_layer_caching: false

      # Build the Docker image using Dockerfile
      - run:
          name: Build Docker Image
          command: |
            docker build -t automationimage .

      # # Flush (delete) reports from artifacts
      # - run:
      #     name: Flush Reports from Artifacts
      #     command: |
      #       rm -rf /root/project/qa-stockwell/TestReports/*
      #       ls -al /root/project/qa-stockwell/TestReports


      # Optionally, you can run tests or other commands inside the Docker container
      - run:
          name: Run Tests inside Docker Container
          command: |
            docker run -v /root/project:/home/seluser/stockwellautomation/qa-stockwell/TestReports automationimage
         
    # docker run -v /root/project/qa-stockwell/TestReports:/home/seluser/stockwellautomation/qa-stockwell/TestReports automationimage       
    # docker volume create test_reports_volume
    # docker run -v test_reports_volume:/home/seluser/stockwellautomation/qa-stockwell/TestReports automationimage
    # docker volume inspect test_reports_volume
    # chmod -R +rw /root/project/qa-stockwell
             


      # Store test report files as artifacts
      - store_artifacts:
          #path: ~/test-reports
          path: /root/project
          destination: test-reports

      # List all files in the /root/project/reports folder
      - run:
          name: List Files in the Folder
          command: |
            pwd
            ls -al 
            ls -al /root/project/qa-stockwell/TestReports

# # Flush (delete) reports from artifacts
#       - run:
#           name: Flush Reports from Artifacts
#           command: |
#             rm -rf /root/project/qa-stockwell/TestReports/*

workflows:
  version: 2
  build:
    jobs:
      - build
      
