version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable

    steps:
      - checkout

      # Install Docker client inside the CircleCI Docker executor
      - setup_remote_docker
      
      # Build the Docker image using Dockerfile
      - run:
          name: Build Docker Image
          command: |
            docker build -t my-docker-image .

      # Optionally, you can run tests or other commands inside the Docker container
      - run:
          name: Run Tests inside Docker Container
          command: |
            docker run my-docker-image npm test  # Example command to run tests

workflows:
  version: 2
  build:
    jobs:
      - build
