version: 2.1

jobs:
  build:
    docker:
      - image: docker:stable

    steps:
     
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Build Docker Image
          command: |
            docker build -t automationimage .
            
      - run:
          name: Run Tests inside Docker Container
          command: |
            # docker run -v /root/project/qa-stockwell/TestReports:/home/seluser/stockwellautomation/qa-stockwell/TestReports automationimage 
            docker run --name automation_container automationimage

      - run:
          name: Copy Files from Container
          command: |
            docker cp automation_container:/home/seluser/stockwellautomation/qa-stockwell/TestReports /root/project/qa-stockwell/TestReports

      - store_artifacts:
          path: /root/project/qa-stockwell/TestReports
          destination: test-reports

workflows:
  version: 2
  build:
    jobs:
      - build
